### ISSUE TITLE
main 应用的 router 模式 支持设置成 hash 吗

### ISSUE THREAD

**Issue by lichenabson** [gongshun/qiankun-vue-demo#18]
目前 主应用的 router mode 设置成 hash
在微应用中 点击 切换 路由, 会导致整体页面都404

**Comment by gongshun** [comment]
https://juejin.cn/post/6856569463950639117#heading-20

**Comment by gongshun** [comment]
https://github.com/gongshun/qiankun-vue-demo/tree/feature/hash-router
