### ISSUE TITLE
主应用删除element-ui样式的cdn引入后，element-ui的iconfont引入失败

### ISSUE THREAD

**Issue by xiejiaxin007** [gongshun/qiankun-vue-demo#48]
主应用删除element-ui样式的cdn引入后，element-ui的iconfont引入失败
![image](https://user-images.githubusercontent.com/22537648/134863131-636b4f78-da20-4c18-8a2b-ff542da902c4.png)

**Comment by gongshun** [comment]
主应用的publicPath配置有问题，你把修改后的代码发出来看一下？

**Comment by xiejiaxin007** [comment]
这个是直接运行你的代码出现的问题，我只是把你主应用中element-ui的cdn删除了，每个子应用都有cdn

**Comment by gongshun** [comment]
> 是直接运行你的代码出现的问题，我只是把你主应用中element-ui的cdn删除了，每个子应用都有cdn

字体文件引入失败的原因：https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

解决办法主要有以下三种：
1. 主应用使用代理，将字体文件的请求转发到CDN上
2. 将CDN的文件下载到自己服务器上，将css里面的字体文件路径改为绝对路径
3. 不使用cdn，直接使用npm包
